[2024-05-21T16:32:19.649+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T16:32:19.666+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:32:19.669+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:32:19.670+0530] {taskinstance.py:2306} INFO - Starting attempt 5 of 5
[2024-05-21T16:32:20.018+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): email_notify> on 2024-05-21 09:12:34.180878+00:00
[2024-05-21T16:32:20.022+0530] {standard_task_runner.py:63} INFO - Started process 94205 to run task
[2024-05-21T16:32:20.023+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'email_notify', 'manual__2024-05-21T09:12:34.180878+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpreiwf35v']
[2024-05-21T16:32:20.024+0530] {standard_task_runner.py:91} INFO - Job 56: Subtask email_notify
[2024-05-21T16:32:20.557+0530] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [running]> on host prince-5192
[2024-05-21T16:32:20.658+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='prince.yadav@tothenew.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='email_notify' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T09:12:34.180878+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T09:12:34.180878+00:00'
[2024-05-21T16:32:20.659+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T16:32:20.673+0530] {logging_mixin.py:188} WARNING - /home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-05-21T16:32:20.673+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-21T16:32:39.782+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T16:32:39.783+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d2e1a72fcca58-6f6a5ba6f5bsm4874203b3a.190 - gsmtp')
[2024-05-21T16:32:39.787+0530] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=email_notify, run_id=manual__2024-05-21T09:12:34.180878+00:00, execution_date=20240521T091234, start_date=20240521T110219, end_date=20240521T110239
[2024-05-21T16:32:39.849+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 56 for task email_notify ((534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor d2e1a72fcca58-6f6a5ba6f5bsm4874203b3a.190 - gsmtp'); 94205)
[2024-05-21T16:32:39.887+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T16:32:39.893+0530] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T16:32:39.893+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
