[2024-05-21T16:27:07.104+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-21T16:27:07.117+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:27:07.120+0530] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [queued]>
[2024-05-21T16:27:07.120+0530] {taskinstance.py:2306} INFO - Starting attempt 4 of 5
[2024-05-21T16:27:07.183+0530] {taskinstance.py:2330} INFO - Executing <Task(EmailOperator): email_notify> on 2024-05-21 09:12:34.180878+00:00
[2024-05-21T16:27:07.187+0530] {standard_task_runner.py:63} INFO - Started process 92614 to run task
[2024-05-21T16:27:07.189+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dag', 'email_notify', 'manual__2024-05-21T09:12:34.180878+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpt6x6blhl']
[2024-05-21T16:27:07.190+0530] {standard_task_runner.py:91} INFO - Job 55: Subtask email_notify
[2024-05-21T16:27:07.293+0530] {task_command.py:426} INFO - Running <TaskInstance: etl_dag.email_notify manual__2024-05-21T09:12:34.180878+00:00 [running]> on host prince-5192
[2024-05-21T16:27:07.391+0530] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='prince.yadav@tothenew.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='email_notify' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T09:12:34.180878+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-21T09:12:34.180878+00:00'
[2024-05-21T16:27:07.392+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-21T16:27:07.407+0530] {logging_mixin.py:188} WARNING - /home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-05-21T16:27:07.408+0530] {email.py:271} INFO - Email alerting: attempt 1
[2024-05-21T16:27:14.877+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-21T16:27:14.878+0530] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/prince/airflow-workspace/env/lib/python3.10/site-packages/airflow/utils/email.py", line 281, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/lib/python3.10/smtplib.py", line 750, in login
    raise last_exception
  File "/usr/lib/python3.10/smtplib.py", line 739, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.10/smtplib.py", line 662, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 98e67ed59e1d1-2b6711660b9sm21632580a91.14 - gsmtp')
[2024-05-21T16:27:14.880+0530] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=email_notify, run_id=manual__2024-05-21T09:12:34.180878+00:00, execution_date=20240521T091234, start_date=20240521T105707, end_date=20240521T105714
[2024-05-21T16:27:15.040+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task email_notify ((534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 98e67ed59e1d1-2b6711660b9sm21632580a91.14 - gsmtp'); 92614)
[2024-05-21T16:27:15.070+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-21T16:27:15.129+0530] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-21T16:27:15.129+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
